### ISSUE TITLE
Do a shellcheck

### ISSUE THREAD

**Issue by ura43** [foss-mreo92/rizon_nibl#3]
To avoid weird errors down the line and improve maintainability, run the thing through shellcheck with no further options and adapt the script to be as close to best practices as possible without compromising functionality.

**Comment by port19x** [comment]
I'm keeping this one open. 
If you don't want to do it yourself I can invest an evening and then open a pull request.
You may want to consider marking this repo as "read-only" if you don't intend on doing any further development but want to keep it online for archival purposes

**Comment by port19x** [comment]
Considering this project dead.
Archive it when you rise from the dead
